### ISSUE TITLE
Move scripts to bottom of HTML for optimization purposes

### ISSUE THREAD

**Issue by thoughtpalette** [whob13/ericwhobrey.com#2]
JS in head will block DOM loading until scripts are resolved. Move these three scripts to the bottom of the HTML document right before closing body tag.

https://github.com/whob13/ericwhobrey.com/blob/master/index.html#L24

**Comment by whob13** [comment]
Resolved with [check in number 4]https://github.com/whob13/ericwhobrey.com/commit/334d2537fd6505e0c2d0664da9e3d830ee3d9821
